// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB16PDyXF8y_1e4rpGteNDvrQa6XsVXAc',
    appId: '1:15135375690:web:9d0b801fd325b2505141b3',
    messagingSenderId: '15135375690',
    projectId: 'untitled3-cf3b6',
    authDomain: 'untitled3-cf3b6.firebaseapp.com',
    storageBucket: 'untitled3-cf3b6.appspot.com',
    measurementId: 'G-DGR00MMKNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBruCQ1CMXoXaHuugXxVadHBFfh5Rl32-o',
    appId: '1:15135375690:android:dfdb7cf130f751325141b3',
    messagingSenderId: '15135375690',
    projectId: 'untitled3-cf3b6',
    storageBucket: 'untitled3-cf3b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9aOxUM14V44mN8fjsghBss7gFLh5TnRA',
    appId: '1:15135375690:ios:02c1ae062beadf935141b3',
    messagingSenderId: '15135375690',
    projectId: 'untitled3-cf3b6',
    storageBucket: 'untitled3-cf3b6.appspot.com',
    iosBundleId: 'com.example.untitled3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9aOxUM14V44mN8fjsghBss7gFLh5TnRA',
    appId: '1:15135375690:ios:e1307be97057b7a85141b3',
    messagingSenderId: '15135375690',
    projectId: 'untitled3-cf3b6',
    storageBucket: 'untitled3-cf3b6.appspot.com',
    iosBundleId: 'com.example.untitled3.RunnerTests',
  );
}
